name: pi-challenge-env
channels:
  - default
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.3
  - ipython=7.12.0
  - jupyter=1.0.0
  - jupyterlab=3.2.4
  - jupyter_contrib_nbextensions
  - numpy=1.24.2
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pip=23.0.1
  - pip:
    - scikit-learn==1.2.2
    - sklearn-pandas==2.2.0
    - missingno==0.5.2
